### ISSUE TITLE
Broken with net-http-persistent 3.0

### ISSUE THREAD

**Issue by uppfinnarn** [patant/fluent-plugin-loggly#21]
```
2016-10-08 01:43:31 +0000 [error]: unexpected error error_class=ArgumentError error=#<ArgumentError: wrong number of arguments (given 2, expected 0)>
  2016-10-08 01:43:31 +0000 [error]: /home/fluent/.gem/ruby/2.3.0/gems/net-http-persistent-3.0.0/lib/net/http/persistent.rb:505:in `initialize'
  2016-10-08 01:43:31 +0000 [error]: /home/fluent/.gem/ruby/2.3.0/gems/fluent-plugin-loggly-0.0.8/lib/fluent/plugin/out_loggly.rb:37:in `new'
  2016-10-08 01:43:31 +0000 [error]: /home/fluent/.gem/ruby/2.3.0/gems/fluent-plugin-loggly-0.0.8/lib/fluent/plugin/out_loggly.rb:37:in `start'
  2016-10-08 01:43:31 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.29/lib/fluent/agent.rb:71:in `block in start'
  2016-10-08 01:43:31 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.29/lib/fluent/agent.rb:70:in `each'
  2016-10-08 01:43:31 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.29/lib/fluent/agent.rb:70:in `start'
  2016-10-08 01:43:31 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.29/lib/fluent/root_agent.rb:108:in `start'
  2016-10-08 01:43:31 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.29/lib/fluent/engine.rb:237:in `start'
  2016-10-08 01:43:31 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.29/lib/fluent/engine.rb:187:in `run'
  2016-10-08 01:43:31 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.29/lib/fluent/supervisor.rb:570:in `run_engine'
  2016-10-08 01:43:31 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.29/lib/fluent/supervisor.rb:162:in `block in start'
  2016-10-08 01:43:31 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.29/lib/fluent/supervisor.rb:366:in `main_process'
  2016-10-08 01:43:31 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.29/lib/fluent/supervisor.rb:339:in `block in supervise'
  2016-10-08 01:43:31 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.29/lib/fluent/supervisor.rb:338:in `fork'
  2016-10-08 01:43:31 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.29/lib/fluent/supervisor.rb:338:in `supervise'
  2016-10-08 01:43:31 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.29/lib/fluent/supervisor.rb:156:in `start'
  2016-10-08 01:43:31 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.29/lib/fluent/command/fluentd.rb:173:in `<top (required)>'
  2016-10-08 01:43:31 +0000 [error]: /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  2016-10-08 01:43:31 +0000 [error]: /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  2016-10-08 01:43:31 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.29/bin/fluentd:5:in `<top (required)>'
  2016-10-08 01:43:31 +0000 [error]: /usr/bin/fluentd:23:in `load'
  2016-10-08 01:43:31 +0000 [error]: /usr/bin/fluentd:23:in `<main>'
```

**Comment by njam** [comment]
There's a fix ready in https://github.com/patant/fluent-plugin-loggly/pull/20

**Comment by patant** [comment]
Fixed in version 0.0.9.

**Comment by sagar-babar** [comment]
@patant Still we are facing issue after upgrading to 0.0.9

**Comment by phagunbaya** [comment]
Me too. 

This is my Dockerfile

```
FROM ubuntu:14.04

RUN ulimit -n 65536

# Disable prompts from apt.
ENV DEBIAN_FRONTEND noninteractive

# Install prerequisites.
RUN apt-get update && \
    apt-get install -y -q curl make g++ && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Install Fluentd.
RUN /usr/bin/curl -L https://td-toolbelt.herokuapp.com/sh/install-ubuntu-trusty-td-agent2.sh | sh

RUN sed -i -e "s/USER=td-agent/USER=root/" -e "s/GROUP=td-agent/GROUP=root/" /etc/init.d/td-agent

RUN td-agent-gem install fluent-plugin-kubernetes_metadata_filter net-http-persistent fluent-plugin-loggly

# Copy the Fluentd configuration file.
COPY td-agent.conf /etc/td-agent/td-agent.conf

# Environment variables for configuration
ENV LOGGLY_URL xyz
ENV FLUENTD_ARGS --use-v1-config

# Run the Fluentd service.
ENTRYPOINT "exec" "td-agent" "$FLUENTD_ARGS"
```

td-agent.conf
```
<source>
  type tail
  path /var/log/containers/*.log
  pos_file /var/log/elastic-containers.log.pos
  time_format %Y-%m-%dT%H:%M:%S
  tag kubernetes.*
  format json
  read_from_head true
</source>

<filter kubernetes.**>
  type kubernetes_metadata
</filter>

<match **>
  type loggly
  logstash_format true
  loggly_url "#{ENV['LOGGLY_URL']}"
  buffer_chunk_limit 2M
  # Cap buffer memory usage to 2MiB/chunk * 32 chunks = 64 MiB
  buffer_queue_limit 32
  flush_interval 5s
</match>
```

Logs:
```
2017-07-15 23:41:43 +0000 [error]: unexpected error error_class=ArgumentError error=#<ArgumentError: wrong number of arguments (2 for 0)>
  2017-07-15 23:41:43 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/net-http-persistent-3.0.0/lib/net/http/persistent.rb:505:in `initialize'
  2017-07-15 23:41:43 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-loggly-0.0.9/lib/fluent/plugin/out_loggly.rb:37:in `new'
  2017-07-15 23:41:43 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-loggly-0.0.9/lib/fluent/plugin/out_loggly.rb:37:in `start'
  2017-07-15 23:41:43 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/lib/fluent/agent.rb:71:in `block in start'
  2017-07-15 23:41:43 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/lib/fluent/agent.rb:70:in `each'
  2017-07-15 23:41:43 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/lib/fluent/agent.rb:70:in `start'
  2017-07-15 23:41:43 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/lib/fluent/root_agent.rb:108:in `start'
  2017-07-15 23:41:43 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/lib/fluent/engine.rb:237:in `start'
  2017-07-15 23:41:43 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/lib/fluent/engine.rb:187:in `run'
  2017-07-15 23:41:43 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/lib/fluent/supervisor.rb:570:in `run_engine'
  2017-07-15 23:41:43 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/lib/fluent/supervisor.rb:162:in `block in start'
  2017-07-15 23:41:43 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/lib/fluent/supervisor.rb:366:in `call'
  2017-07-15 23:41:43 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/lib/fluent/supervisor.rb:366:in `main_process'
  2017-07-15 23:41:43 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/lib/fluent/supervisor.rb:339:in `block in supervise'
  2017-07-15 23:41:43 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/lib/fluent/supervisor.rb:338:in `fork'
  2017-07-15 23:41:43 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/lib/fluent/supervisor.rb:338:in `supervise'
  2017-07-15 23:41:43 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/lib/fluent/supervisor.rb:156:in `start'
  2017-07-15 23:41:43 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/lib/fluent/command/fluentd.rb:173:in `<top (required)>'
  2017-07-15 23:41:43 +0000 [error]: /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  2017-07-15 23:41:43 +0000 [error]: /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  2017-07-15 23:41:43 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.35/bin/fluentd:5:in `<top (required)>'
  2017-07-15 23:41:43 +0000 [error]: /opt/td-agent/embedded/bin/fluentd:23:in `load'
  2017-07-15 23:41:43 +0000 [error]: /opt/td-agent/embedded/bin/fluentd:23:in `<top (required)>'
  2017-07-15 23:41:43 +0000 [error]: /usr/sbin/td-agent:7:in `load'
  2017-07-15 23:41:43 +0000 [error]: /usr/sbin/td-agent:7:in `<main>'
2017-07-15 23:41:43 +0000 [info]: shutting down fluentd
```
